# keywords.py

int_keywords = [
    "id",
    "number",
    "count",
    "total",
    "likes",
    "clicks",
    "impr",
    "visits",
    "quantity",
    "unit",
    "conversions",
    "viewable_impressions",
    "media_cost",
    "interactions",
    "swipes",
    "transactions",
    "rich_media",
    "views",
    "n03",
    "n04",
    "n05",
    "n06",
    "n01",
    "stars",
    "quartile",
    "rating",
    "player_errors",
    "player_skip",
    "player_unmute",
    "player_resume",
    "player_engaged_views",
    "unsubscribes",
    "followers",
    "member",
    "campaign_count",
    "total_followers_count",
]


string_keywords = [
    "name",
    "description",
    "title",
    "text",
    "engine",
    "account",
    "currency_code",
    "campaign",
    "location",
    "user",
    "api",
    "adset",
    "destination",
    "distribution",
    "status",
    "code",
    "add_on",
    "uuid",
    "conversion",
    "medium",
    "content",
    "user_type",
    "device",
    "source",
    "advertisement",
    "placement",
    "publisher",
    "delivery_channel",
    "tactic",
    "flight",
    "activity",
    "site",
    "cost_model",
    "video",
    "dimension",
    "click_through",
    "brand",
    "landing_page",
    "client_ip",
    "query",
    "user_agent",
    "referrer",
    "strategy",
    "platform",
    "creative",
    "adgroup",
    "channel",
    "ad_type",
    "post_type",
    "ad_group",
    "keyword",
    "rich_media",
    "click_delivery",
    "asset",
    "asset_category",
    "browser_platform",
    "content_category",
    "ad_status",
    "placement_strategy",
    "ad",
    "placement_compatibility",
    "connection_type",
    "browser",
    "creative_group",
    "line_item_status",
    "match_type",
    "ad_network_type",
    "conversion_source",
    "conversion_category",
    "customer_id",
    "goal_type",
    "neighborhood",
    "folder_name",
    "message_id",
    "call_type",
    "attachment_video",
    "earned_impressions",
    "conversion",
    "swipe_up_attribution_window",
    "view_time_millis",
    "video_views_time_based",
    "screen_time_millis",
    "optimization_goal",
    "view_attribution_window",
    "frequency",
    "vanity_name",
    "organization_type",
    "organizational_entity_type",
    "organizational_entity",
    "localized_website",
    "localized_name",
    "player",
    "advertiser_currency_code",
    "partner_cost_usd",
    "ad_group_budget_adv_currency",
    "total_bid_amount_usd",
    "advertiser_cost_partner_currency",
]


date_keywords = [
    "date",
    "campaign_end_date",
    "campaign_start_date",
    "time",
    "year",
    "month",
    "day",
    "snapshot",
    "start_date",
    "end_date",
]

email_keywords = ["email", "event_guests_email"]

float_keywords = [
    "cost",
    "spend",
    "revenue",
    "cpc",
    "conversion_rate",
    "gross_ecpa",
    "gross_ecpc",
    "gross_ecpm",
    "ctr",
    "conversion_value",
    "profit",
    "post_click_conversions",
    "effective_cpm",
    "revenue_per_click",
    "revenue_per_thousand_impressions",
    "dbm_cost",
    "active_view_impressions",
    "rich_media_manual_closes",
    "rich_media_expansions",
    "rich_media_video_mutes",
    "rich_media_full_screen_impressions",
    "rich_media_clicks",
    "planned_media_cost",
    "rich_media_event_counters",
    "rich_media_average_expansion_time",
    "rich_media_video_stops",
    "rich_media_interaction_rate",
    "rich_media_interactions",
    "rich_media_average_full_screen_view_time",
    "rich_media_full_screen_video_plays",
    "view_through_conversions",
    "activity_per_thousand_impressions",
    "click_through_revenue",
    "rich_media_video_progress_events",
    "total_conversions_revenue",
    "rich_media_video_pauses",
    "rich_media_custom_average_time",
    "view_through_revenue",
    "rich_media_average_display_time",
    "rich_media_video_interaction_rate",
    "video_length",
    "dbm_cost_usd",
    "click_rate",
    "video_first_quartile_completions",
    "activity_per_click",
    "video_third_quartile_completions",
    "rich_media_expansion_time",
    "rich_media_custom_timers",
    "mediacost",
    "rich_media_video_view_rate",
    "rich_media_video_completions",
    "video_cta_clicks",
    "likes",
    "media_engagements",
    "url_clicks",
    "app_clicks",
    "replies",
    "billed_engagements",
    "conversion_purchases",
    "video_total_views",
    "billed_charge_local_micro",
    "engagements",
    "media_views",
    "rate",
    "click_through_rate",
]


keyword_ranges = {
    "age": (0, 150),
    "clicks": (1, 10000),
    "rating": (1, 5),
    "stars": (1, 5),
    "quartile": (1, 4),
    "campaign_count": (1, 10000),
    "member_count": (0, 100000),
    "total_followers_count": (0, 1000000),
    "player_errors": (0, 1000),
    "video_length": (1, 10000),
    "likes": (0, 1000000),
    "media_engagements": (0, 1000000),
    "total_bid_amount_usd": (0, 10000000),
    "total_revenue": (0, 10000000),
    "rate": (0.0, 1.0),
}

dictionary_keywords = {
    "countries": ["country", "nation", "state", "location"],
    "customers": ["customer", "client", "user", "customers", "name"],
    "companies": ["company", "business", "organization", "companies", "campaign_name"],
}
